# Generated by Django 3.1.2 on 2020-10-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paf',
            fields=[
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('numeroConvenio', models.CharField(max_length=50)),
                ('convenio', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(max_length=50)),
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('tipo_bono', models.CharField(max_length=50)),
                ('formulario', models.CharField(max_length=50)),
                ('fecha_expedicion', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.CharField(max_length=50)),
                ('fecha_caducidad', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
