# Generated by Django 3.1.2 on 2020-10-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportarPAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=50)),
                ('file_name', models.FileField(upload_to='excel')),
                ('timestamp', models.DateField(auto_now=True)),
                ('subido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('serial', models.BigIntegerField()),
                ('numeroConvenio', models.CharField(max_length=255)),
                ('convenio', models.BigIntegerField()),
                ('tipo_doc', models.CharField(max_length=255)),
                ('documento', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_bono', models.CharField(max_length=255)),
                ('formulario', models.CharField(max_length=255)),
                ('fecha_expedicion', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.CharField(max_length=255)),
                ('fecha_caducidad', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
