# Generated by Django 3.1.2 on 2020-10-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('departamento_municipio', models.CharField(max_length=50)),
                ('person_id', models.CharField(max_length=50)),
                ('ciclo', models.IntegerField()),
                ('convenio', models.IntegerField()),
                ('tipo_doc', models.CharField(max_length=50)),
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('tipo_bono', models.CharField(max_length=50)),
                ('formulario', models.IntegerField()),
                ('fecha_expedicion', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.CharField(max_length=50)),
                ('fecha_caducidad', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('scope_account', models.CharField(max_length=50)),
                ('scope_payment_st', models.CharField(max_length=50)),
                ('scope_payment_dt', models.CharField(max_length=50)),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportarCAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=50)),
                ('file_name', models.FileField(upload_to='excel')),
                ('timestamp', models.DateField(auto_now=True)),
                ('subido', models.BooleanField(default=False)),
            ],
        ),
    ]
