# Generated by Django 3.1.2 on 2020-10-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('departamento_municipio', models.CharField(max_length=50)),
                ('person_id', models.CharField(max_length=50)),
                ('ciclo', models.IntegerField()),
                ('convenio', models.IntegerField()),
                ('tipo_doc', models.CharField(max_length=50)),
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('tipo_bono', models.CharField(max_length=50)),
                ('formulario', models.IntegerField()),
                ('fecha_expedicion', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.CharField(max_length=50)),
                ('fecha_caducidad', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('scope_account', models.CharField(max_length=50)),
                ('scope_payment_st', models.CharField(max_length=50)),
                ('scope_payment_dt', models.CharField(max_length=50)),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
